# Generated by Django 3.1.3 on 2021-02-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tweet_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=50)),
                ('model', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'tweet_models',
            },
        ),
    ]
