# Generated by Django 3.1.3 on 2021-02-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_crawler', '0002_tweet_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet_models',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tweet_models',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
