"""
Django settings for cappers_collective project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import django_heroku
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=pl47msg!#$hjt%waq-t$k$_-&r$0%4rd&c!i^=n(aer=fxd(b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tweet_crawler',
    #'admin_reorder'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'admin_reorder.middleware.ModelAdminReorder',
]

ROOT_URLCONF = 'cappers_collective.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cappers_collective.wsgi.application'

#ADMIN_REORDER = (
#    {'app': 'auth', 'label': 'Users/Groups'},
#
#   
#    {'app': 'tweet_crawler', 'label': 'Twitter Data',
#     'models': ({'model': 'tweet_crawler.twitter_users', 'label': 'Twitter Users'},
#     )},
#
#    {'app': 'tweet_crawler', 'label': 'Initial Crawl Data',
#     'models': ({'model': 'tweet_crawler.tweets_all', 'label': 'ALL Tweets'},
#                {'model': 'tweet_crawler.tweet_models', 'label': 'BET Tweet Models'},
#     )},
#
#    
#
#    {'app': 'tweet_crawler', 'label': 'Bet Tweet Data',
#     'models': ( {'model': 'tweet_crawler.tweets_bets', 'label': 'BET Tweets'},
#                 {'model': 'tweet_crawler.bet_line_models', 'label': 'BET Line Models'},
#               
#     )},
#
#    {'app': 'tweet_crawler', 'label': 'Win/Loss Models',
#     'models': ({'model': 'tweet_crawler.win_models', 'label': 'Win Models'},
#                {'model': 'tweet_crawler.loss_models', 'label': 'Loss Models'},
#     )},
#
#
#    {'app': 'tweet_crawler', 'label': 'League Models',
#     'models': ({'model': 'tweet_crawler.nfl_models', 'label': 'NFL Models'},
#                {'model': 'tweet_crawler.nba_models', 'label': 'NBA Models'},
#                {'model': 'tweet_crawler.mlb_models', 'label': 'MLB Models'},
#                {'model': 'tweet_crawler.nhl_models', 'label': 'NHL Models'},
#                {'model': 'tweet_crawler.ncaaf_models', 'label': 'NCAAF Models'},
#                {'model': 'tweet_crawler.ncaab_models', 'label': 'NCCAB Models'},
#     )
#    },
#    {'app': 'tweet_crawler', 'label': 'Final Data',
#     'models': ({'model': 'tweet_crawler.parsed_data', 'label': 'Final Tweet Data'},
#     )},
#)

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'd1acr589hq47f4',
        'USER': 'jlkghpyceaceaj',
        'PASSWORD': '5d3ff149d535057886dfd52ac85888eb2f28f2ba34c5f36b46429d99720f7f36',
        'HOST': 'ec2-54-82-208-124.compute-1.amazonaws.com',
        'PORT': '',
    }   
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_ROOT = ''

STATIC_URL = '/static/'

STATICFILES_DIRS = ( os.path.join('static'), )

# Activate Django-Heroku.
django_heroku.settings(locals())